### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by Aziona** [miikaforma/ENTSO-ELogger#2]
Hi, I am trying to use docker-compose but I am getting this error.
```
 thread 'main' panicked at src/logging.rs:89:18:
entsoe_logger_1   | called `Result::unwrap()` on an `Err` value: OutputIo(Os { code: 13, kind: PermissionDenied, message: "Permission denied" })
entsoe_logger_1   | note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Any idea what might go wrong? This is my docker-compose section. Influxdb 1.8 runs on 192.168.178.106 and is working for other purposes. I created a database named test.

```
  entsoe_logger:
    restart: unless-stopped
    image: miikaforma/entsoe-logger:latest
    ports:
     - 9092:9092
    environment:
      # ENTSO-E API token
      SECURITY_TOKEN: "670001ba-3b3d-4dec-8360-b9e92213xxxx"
      # ENTSO-E API parameters
      IN_DOMAIN: 10YFI-1--------U
      OUT_DOMAIN: 10YFI-1--------U
      # How often to fetch data (in milliseconds)
      INTERVAL: 3600000 # 3600000 = 1 hour | 10000 = 10 seconds
      # How many days to fetch (start time + interval days)
      INTERVAL_DAYS: 1
      # Start time for fetching data (will only be used if no newer data is found from the database(s))
      START_TIME: '2024-01-01T00:00Z'

      # InfluxDB storage
      INFLUXDB_ENABLED: 'true'
      DATABASE_URL: http://192.168.178.106:8086
      DATABASE_NAME: test

      # TimeScale DB storage
      TIMESCALEDB_ENABLED: 'true'
      TIMESCALEDB_CONNECTION_STRING: "host=192.168.178.106 user=admin password=Secret1234 dbname=test"

      # Operation modes
      ENABLE_REST_API: 'true'
      ENABLE_AUTO_UPDATE: 'true'
```

**Comment by miikaforma** [comment]
@Aziona 

Hi, it seems like I've made some changes along the way and forgot to document them. For a quick fix, you need to add these volumes to your docker compose file:

```
    ports:
      - 9092:9092
...
    volumes:
      - ./configs:/configs:ro
      - ./logs:/logs/:rw
...
    environment:
```

And then create `logs` -folder in the same directory as where you have the compose file. And also create `configs` directory which has `production.yaml` file with for example the following content:
```
settings:
  - start_time: "2022-11-30T22:00:00"
    end_time: "2023-04-30T20:59:59"
    tax_percentage: 10
  - start_time: "2023-04-30T21:00:00"
    end_time: "2024-08-31T20:59:59"
    tax_percentage: 24
  - start_time: "2024-08-31T21:00:00"
    tax_percentage: 25.5
```

I'll try to document this stuff once off from work but these additions should make it work (just tested it).
